[project]
name = "minichat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "colorama>=0.4.6",
    "configargparse>=1.7.1",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
]
